project_id = "hdyuuykxujqjrpthswbi"

[functions.create-checkout-session]
verify_jwt = false

[functions.complete-payment]
verify_jwt = false

[functions.activate-scheduled-campaigns]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
